# Site settings
title: Beom's Personal Website
email: beom8776@naver.com
description: Beom's Dev Blogs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: beomseok90
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/beomseok90/beomseok90.github.io/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/beomseok90/beomseok90.github.io/new/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: beomseok90
#duoshuo_url: "http://beomseok90.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: beomseok90
disqus_url: "http://beomseok90.github.io"
#########################################

#google analytics
google_analytics:
  ua: 'UA-134336607-1'

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
